server:
  port: 8400

spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${matchpass.config.kafka.server-url}
    admin:
      fail-fast: false

matchpass:
  config:
    kafka:
      server-url: localhost:29092
      consumer-groups:
        pagamento-solicitado: payment-service-payment-requested
      topics:
        pagamento-solicitado: matchpass.payment.requested.v1
        sessao-pagamento-criada: matchpass.payment.session-created.v1
        pagamento-aprovado: matchpass.payment.approved.v1
        pagamento-falhou: matchpass.payment.failed.v1

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs