server:
  port: 8600

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs

notification:
  frontend-url: http://localhost:5500

  email:
    sender-email: ${NOTIFICATION_EMAIL}
    sender-name: Reservae

    assets:
      payment-background-url: ${PAYMENT_BACKGROUND_URL}
      payment-header-illustration-url: ${PAYMENT_HEADER_ILLUSTRATION_URL}
      payment-footer-illustration-url: ${PAYMENT_FOOTER_ILLUSTRATION_URL}
      instagram-icon-url: ${INSTAGRAM_ICON_URL}

brevo:
  api:
    url: https://api.brevo.com/v3
    key: ${BREVO_API_KEY}

reservae:
  config:
    kafka:
      server-url: localhost:29092
      consumer-groups:
        notificacao-pagamento-pendente: notification-service-payment-pending-notification
        notificacao-pagamento-confirmado: notification-service-payment-confirmed-notification
        notificacao-pagamento-falhou: notification-service-payment-failed-notification
        ingresso-gerado: notification-service-ticket-generated
      topics:
        notificacao-pagamento-pendente: reservae.notification.payment-pending-requested.v1
        notificacao-pagamento-confirmado: reservae.notification.payment-confirmed-requested.v1
        notificacao-pagamento-falhou: reservae.notification.payment-failed-requested.v1
        ingresso-gerado: reservae.ticket.generated.v1