server:
  port: 8300

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs

matchpass:
  config:
    kafka:
      server-url: localhost:29092
      consumer-group: order-service-inventory-reservation
      topics:
        reserva-solicitada: matchpass.order.reservation-requested.v1
        resultado-reserva: matchpass.inventory.reservation-result.v1