server:
  port: 8300

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${matchpass.config.kafka.server-url}
    admin:
      fail-fast: false

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs

matchpass:
  config:
    kafka:
      server-url: localhost:29092
      consumer-groups:
        resultado-reserva: order-service-reservation-result
        sessao-pagamento-criada: order-service-payment-session-created
        pagamento-aprovado: order-service-payment-approved
        pagamento-falhou: order-service-payment-failed
      topics:
        reserva-solicitada: matchpass.order.reservation-requested.v1
        resultado-reserva: matchpass.inventory.reservation-result.v1
        sessao-pagamento-criada: matchpass.payment.session-created.v1
        pagamento-solicitado: matchpass.payment.requested.v1
        pagamento-aprovado: matchpass.payment.approved.v1
        pagamento-falhou: matchpass.payment.failed.v1
        notificacao-pagamento-pendente: matchpass.notification.payment-pending-requested.v1
        notificacao-pagamento-confirmado: matchpass.notification.payment-confirmed-requested.v1
        notificacao-pagamento-falhou: matchpass.notification.payment-failed-requested.v1
        pedido-confirmado: matchpass.order.confirmed.v1