server:
  port: 8300

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs

matchpass:
  config:
    kafka:
      server-url: 'http://localhost:29092'
      topics:
        pedidos-criados: 'matchpass.pedidos-criados'
        pedidos-pagos: 'matchpass.pedidos-pagos'