server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: event-catalog-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev

resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
      foo-bar:
        max-concurrent-calls: 20
  retry:
    instances:
      foo-bar:
        max-attempts: 7
        wait-duration: 1s
        enable-exponential-backoff: true

springdoc:
  api-docs:
    path: /event-catalog-service/v3/api-docs
  override-server-url: true