server:
  port: 8500

spring:
  application:
    name: ticket-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

matchpass:
  config:
    kafka:
      server-url: localhost:29092
      consumer-groups:
        pedido-confirmado: ticket-service-order-confirmed
      topics:
        pedido-confirmado: matchpass.order.confirmed.v1
        ingresso-gerado: matchpass.ticket.generated.v1

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs