server:
  port: 8600

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs

notification:
  email:
    sender-email: ${NOTIFICATION_EMAIL}
    sender-name: MatchPass

brevo:
  api:
    url: https://api.brevo.com/v3
    key: ${BREVO_API_KEY}