server:
  port: 8600

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs

notification:
  frontend-url: http://localhost:5500

  email:
    sender-email: ${NOTIFICATION_EMAIL}
    sender-name: MatchPass

    assets:
      payment-background-url: https://seu-dominio.com/email/payment-background.png
      payment-header-illustration-url: https://seu-dominio.com/email/payment-header.png
      payment-footer-illustration-url: https://seu-dominio.com/email/payment-footer.png

      facebook-icon-url: https://seu-dominio.com/email/facebook.png
      linkedin-icon-url: https://seu-dominio.com/email/linkedin.png
      x-icon-url: https://seu-dominio.com/email/x.png
      instagram-icon-url: https://seu-dominio.com/email/instagram.png
      youtube-icon-url: https://seu-dominio.com/email/youtube.png
      pinterest-icon-url: https://seu-dominio.com/email/pinterest.png

brevo:
  api:
    url: https://api.brevo.com/v3
    key: ${BREVO_API_KEY}

matchpass:
  config:
    kafka:
      server-url: localhost:29092
      consumer-groups:
        sessao-pagamento-criada: notification-service-payment-session-created
      topics:
        sessao-pagamento-criada: matchpass.payment.session-created.v1